version: '2'
services:
  web:
    build: .
    volumes:
      - './app:/app'
    ports:
      - '3030:3000'
    env_file:
      - .env
    environment:
      - PORT=3000
      - ELASTIC_SEARCH_HOST=http://elastic:changeme@172.18.0.2:9200
    depends_on:
      - elastic

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.2
